general {
    hide_cursor = true
    disable_loading_bar = true
    ignore_empty_input = true
    no_fade_in = true
    no_fade_out = true
    grace = 1
}

background {
    monitor =
    path = screenshot 
    # Gruvbox Background (Dark 0)
    background = rgba(40, 40, 40, 0.9);
    blur_passes = 2
    blur_size = 5
}

# --- Clock (Large) ---
label {
    monitor = 
    text = <span weight="heavy" size="xx-large">$TIME</span>
    # Gruvbox Aqua/Blue for the clock highlight
    color = rgba(235, 219, 178, 1.0) 
    font_size = 120
    font_family = DejaVu Sans
    position = 0, 50
    halign = center
    valign = center
}

# --- Login Message ---
label {
    monitor = 
    text = <span weight="heavy" size="xx-large">LogIn, First $DESC</span>
    # Gruvbox Cream (Light 1)
    color = rgba(235, 219, 178, 1.0)
    font_size = 10
    font_family = DejaVu Sans
    position = 0, 127
    halign = center
    valign = center
}

# --- Keyboard Layout ---
label {
    monitor = 
    text = <span weight="heavy" size="xx-large">$LAYOUT</span>
    # Gruvbox Gray
    color = rgba(235, 219, 178, 1.0)
    font_size = 7
    font_family = DejaVu Sans
    position = 10, 10
    halign = left
    valign = bottom
}

# --- Input Field ---
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = 0
    
    # Border: Gruvbox Orange | Inner: Transparent
    outer_color = rgba(235, 219, 178, 1.0) 
    inner_color = rgba(40, 40, 40, 0.0)
    
    # Text and Dots: Gruvbox Yellow
    font_color =  rgba(235, 219, 178, 1.0)
    
    fade_on_empty = true
    fade_timeout = 1000
    hide_input = false
    rounding = 0
    
    # Error state: Gruvbox Red
    fail_color = rgba(251, 73, 52, 1.0)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    
    position = 0, -60
    halign = center
    valign = center
}
